server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://192.168.3.65:3306/cauth?characterEncoding=utf8
      username: root
      password: 111111
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
